copy burntime.ks from 0.
copy circorbit.ks from 0.
copy deorbit.ks from 0.
copy ispcurrent.ks from 0.
copy lander.ks from 0.
copy launch.ks from 0.
copy maneuvernode.ks from 0.
copy neu.ks from 0.
copy rendezvous.ks from 0.
copy test.ks from 0.
copy releaseclamp.ks from 0.
